video:
  path: ''
highlights:
  clip_time: 10
  output: ''
  max_duration: 420
  exact_duration: 0
  keep_temp: false
  skip_highlights: false
scoring:
  scene_points: 0
  motion_event_points: 3
  motion_peak_points: 0
  audio_peak_points: 0
  keyword_points: 2
  transcript_points: 2
  object_points: 1
  action_points: 10
  multi_signal_boost: 1.2
  min_signals_for_boost: 2
actions:
  interesting: []
objects:
  interesting: []
keywords:
  transcript_file: transcript.txt
  interesting: []
transcript:
  enabled: false
  model: base
  search_keywords: []
subtitles:
  enabled: false
  source_lang: en
  target_lang: pl
advanced:
  frame_skip: 5
  object_frame_skip: 10
  yolo_pt_path: ''
  openvino_model_folder: ''
